name: deploy-api-docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
      - name: Setup
        run: haxelib install dox
      - name: Build documentation
        run: |
          haxe api.hxml
          git clone https://github.com/armory3d/armsdk.git
          export ARMORY_SDK=./armsdk
          haxelib run dox -i ./ -o docs --title 'T   R   ⚫  Ͷ' -D themeColor 0x000000 -D textColor 0x000000 -D website 'https://gamma.disktree.net'
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
